name: law_education_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl:
  intl_translation:
  flutter_localizations:
    sdk: flutter
  shared_preferences:
  provider:
  file_picker:
  pdfx:
  firebase_storage:
  cupertino_icons: ^1.0.6
  otp_text_field: ^1.1.3
  animated_bottom_navigation_bar: ^1.3.3
  firebase_auth: ^4.6.0
  firebase_core: ^2.12.1
  google_sign_in:
  http:
  firebase_app_check:
  flutter_pdfview:
  dio:
  url_launcher:
  path_provider:
  cloud_firestore: ^4.8.0
  flutter_keyboard_visibility: ^5.4.0
  flutter_easyloading: ^3.0.5
  provider: ^6.1.2
  image_picker: ^1.1.2
  sn_progress_dialog: ^1.1.4
  firebase_storage: ^11.6.0
  cool_alert: ^2.0.1
  smooth_page_indicator: ^1.2.0+3









  build_runner:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
