name: law_education_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.6
  intl:
  intl_translation:
  flutter_localizations:
    sdk: flutter
  shared_preferences:
  file_picker:
  pdfx:
  cupertino_icons: ^1.0.6
  otp_text_field: ^1.1.3
  animated_bottom_navigation_bar: ^1.3.3
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  google_sign_in:
  http:
  firebase_app_check:
  dio:
  geolocator:
  geocoding:
  url_launcher:
  lottie:
  readmore:
  shimmer: ^3.0.0
  path_provider:
  cloud_firestore: ^5.4.1
  flutter_keyboard_visibility: ^5.4.0
  flutter_easyloading: ^3.0.5
  provider: ^6.1.2
  image_picker: ^1.1.2
  sn_progress_dialog: ^1.1.4
  firebase_storage: ^12.3.0
  cool_alert: ^2.0.1
  smooth_page_indicator: ^1.2.0+3
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  flutter_pdfview: ^1.0.3
  build_runner:
  just_audio:
  permission_handler:
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/assets/

